### ISSUE TITLE
Act 3: Add interactive hover showing stations by region

### ISSUE THREAD

**Issue by themightybruce** [free-radicals/AirPollution#109]
When we hover over a region of the globe the points are highlighted in the same regional colors as the All Cities chart and we show a tooltip with number of cities with measurements by region

Europe: particulate matter data available in 400 cities
North America: particulate matter data available in 600 cities...etc

Lets say **particulate matter** and not PM2.5, since some of our PM2.5 data is actually estimated from PM10 measurements 

This will help reinforce one of the points we will make in Act 3 about the need for greater measurement of data so we know the scale of the problem, especially in Africa

**Comment by dominickp** [comment]
I like the idea but this seems like a tough one. I think we would need a topojson file that has regional designations or we would have to draw regions over the one we have. I think mapping to the color scale used previously would be difficult because we'd have to modify the dataset to have the same region codes as previously used. 

@mariusdv What are your thoughts?

**Comment by mariusdv** [comment]
Because the regions are added to act 3, I don't mind taking a crack at this.

**Comment by mariusdv** [comment]
actual on hovers will be to much work before final submission.
I suggest a simplified version by adding a small table with the data points data underneath the globe.
